allwhat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portal/urls.py
from django.urls import path
from .views import Index, point_datasets, Portal, Persona, PersonaViewDetail, CrearPersonaViewDetail, Incidencia,Login,DniNuevoViewDetail

urlpatterns = [
	path('',Index, name='index'),
	path('incidence_data/', point_datasets, name='incidences'),
	path('incidencia/', Incidencia, name='incidencia'),
	path('personas_data/', Persona, name='personas'),
	path('portal/', Portal, name='portal'),
	path('login-acceso/', Login, name='login'),

	path('persona/', PersonaViewDetail.as_view()),
	path('crearpersona/', CrearPersonaViewDetail.as_view()),

	path('ubigeo/nuevodni/<str:dni>/',DniNuevoViewDetail.as_view()),
]

portal/models.py
from __future__ import unicode_literals
from audioop import max
from django.db import models
from django.contrib.gis.db import models

class TypePerson(models.Model):
    descripcion = models.CharField(max_length=50)
    objects = models.Manager()
    def __str__(self):
        return self.descripcion

class Radio(models.Model):
    descripcion = models.CharField(max_length=10)
    ubicacion = models.PointField(srid=4326)
    def __str__(self):
        return self.descripcion

class Person(models.Model):
    SEXO_CHOICES = [
        ('1','MASCULINO'),
        ('2','FEMENINO'),
    ]
    nombre = models.CharField(max_length=50)
    apepaterno = models.CharField(max_length=50)
    apematerno = models.CharField(max_length=50)
    documento = models.CharField(max_length=8)
    sexo = models.CharField(max_length=1,choices=SEXO_CHOICES)
    fecnacimiento = models.DateField(null=True, blank=True)
    celular = models.CharField(max_length=15,null=True, blank=True)
    direccion = models.CharField(max_length=150, null=True, blank=True)
    radio = models.ForeignKey(Radio,null=True, blank=True, on_delete=models.SET_NULL)
    typeperson = models.ForeignKey(TypePerson, null=True,blank=True,on_delete=models.SET_NULL)
    objects = models.Manager()
    def __str__(self):
        return self.nombre + ' ' + self.apepaterno +' '+ self.apematerno

# Create your models here.
class TypeIncidence(models.Model):
    descripcion = models.CharField(max_length=100)
    abreviatura = models.CharField(max_length=50, null=True,blank=True)
    objects = models.Manager()
    def __str__(self):
        return self.descripcion
    class Meta:
        verbose_name_plural = "Type Incidence"

class Vehiculo(models.Model):
    VEHICULO_CHOICE = [
        ('1','CAMIONETA'),
        ('2','MOTOCICLETA'),
    ]
    ASIGNADO_CHOICE = [
        ('1','ASIGNADO'),
        ('2','NO ASIGNADO'),
    ]
    modelo = models.CharField(max_length=1,null=True,blank=True,choices=VEHICULO_CHOICE)
    placa = models.CharField(max_length=10,null=True,blank=True)
    asignado = models.CharField(max_length=1, null=True, blank=True, choices=ASIGNADO_CHOICE)
    def __str__(self):
        return self.placa

class Incidences(models.Model):
    location = models.PointField(srid=4326)
    objects = models.Manager()
    fecincidencia = models.DateTimeField(auto_now=True)
    fecactuainsidencia = models.DateTimeField(auto_now_add=True)
    agente = models.ForeignKey(Person, related_name="agente",on_delete=models.SET_NULL, null=True,blank=True)
    agraviado = models.ForeignKey(Person, related_name="agraviado",on_delete=models.SET_NULL, null=True, blank=True)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.SET_NULL,null=True,blank=True)
    typeinsidence = models.ForeignKey(TypeIncidence, on_delete=models.SET_NULL,null=True,blank=True)
    def __str__(self):
        return self.typeinsidence.descripcion
    def natural_key(self):
        return self.typeinsidence.natural_key()
    natural_key.dependencies = ['portal.typeincidence']
    class Meta:
        verbose_name_plural = "Incidences"

portal/forms.py
from django.forms import ModelForm
from .models import Incidences

# Create the form class.
class IncidenciaForm(ModelForm):
     class Meta:
         model = Incidences
         fields = ['location', 'agente', 'agraviado', 'typeinsidence','vehiculo']

portal/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.core.serializers import serialize
from django.http import HttpResponse
from .models import Incidences, TypeIncidence, TypePerson, Person, Vehiculo, TypeIncidence
from .forms import IncidenciaForm
from django.utils import timezone
from django.shortcuts import redirect

# Create your views here.
def Login(request):
	return render(request, 'login-acceso.html')

# Create your views here.
def Index(request):
	agente = TypePerson.objects.all()
	contexto = {'agente': agente}
	return render(request, 'index.html',contexto)

def point_datasets(request):
	all_objects = Incidences.objects.all()
	points = serialize('geojson', all_objects)
	return HttpResponse(points,content_type='json')

def Persona(request):
	all_objects = [*Person.objects.all()]
	personas = serialize('json',all_objects)
	return HttpResponse(personas,content_type='json')

def Portal(request):
	incidencias = Person.objects.all()
	vehiculos = Vehiculo.objects.all()
	typeincidence = TypeIncidence.objects.all()
	print(incidencias)
	context = {'incidencias':incidencias,'vehiculos':vehiculos,'typeincidence':typeincidence}
	return render(request, 'portal/index.html', context)


from django.contrib.gis.geos import Point, GEOSGeometry


def Incidencia(request):
	if request.method == "POST":
		persona = Person.objects.get(documento='70033475')
		form = Incidences()
		#post = form.save(commit=False)
		form.agraviado_id = persona.id
		form.agente_id = request.POST['agente_id']
		form.agente_id = request.POST['typeinsidence_id']
		form.typeinsidence_id = request.POST['typeinsidence_id']
		form.vehiculo_id = request.POST['vehiculo_id']
		latitude = request.POST['latitude']
		print(latitude)
		longitude = request.POST['longitude']
		print(longitude)
		form.location = GEOSGeometry('POINT(%s %s), 4326' % (longitude, latitude))
		form.save()
	return redirect("/portal/")

from rest_framework.views import APIView
from rest_framework.response import Response

from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse

class PersonaViewDetail(APIView):
	def post(self, request, format=None):
		post_data = request.data
		persona = Person.objects.get(documento=post_data['dni'])
		contexto = {'nombre': persona.nombre, 'apepaterno': persona.apepaterno, 'apematerno': persona.apematerno}
		datosJson = json.dumps(contexto, sort_keys=True,
							   indent=1,
							   cls=DjangoJSONEncoder)
		return HttpResponse(datosJson, content_type='application/json')

class CrearPersonaViewDetail(APIView):
	def post(self, request, format=None):
		post_data = request.data
		try:
			persona = Person.objects.get(documento=post_data["dni"])
		except Person.DoesNotExist:
			cp = Person()
			cp.documento = post_data["dni"]
			cp.nombre = post_data["nombres"]
			cp.apepaterno = post_data["apepaterno"]
			cp.apematerno = post_data["apematerno"]
			cp.save()
			pass
		return HttpResponse("success")

from django.shortcuts import render, redirect, get_object_or_404
import json

import requests

class DniNuevoViewDetail(APIView):

	def get_object(self,dni):
		return dni

	def get(self, request, dni, format=None):
		s = requests.Session()
		data=''

		if len(dni) == 8:
			get = s.get("http://digital.regionhuanuco.gob.pe/tramite/persona/dni/"+dni)
			data = get.json()

			if len(data) > 1:
				try:
					persona = Person.objects.get(documento=data["dni"])
				except Person.DoesNotExist:
					cp = Person()
					cp.documento = data["dni"]
					cp.nombre = data["prenombres"]
					cp.apepaterno = data["apPrimer"]
					cp.apematerno = data["apSegundo"]
					cp.save()
					pass
			return Response(data)
		else:
			return Response("Ingrese correctamente su DNI")

templates/index.html
{% extends 'template.html' %}
{% load static %}
{% block mapaleaflet %}
	{% load leaflet_tags %}
	{% leaflet_js %}
	{% leaflet_css %}
{% endblock %}

{% block css %}
	<style type="text/css">
		#gis {
		width: 100%;
		height: calc(100vh);
		}
	</style>
	<link rel="stylesheet" type="text/css" href="{% static 'css/easy-button.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'allwhat/css/style.css' %}">
{% endblock %}

{% block jshead %}
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.0.js" ></script>
	<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}" >	</script>
	<script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}" >	</script>
	<script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}" ></script>

	<script type="text/javascript" src="{% static 'js/easy-button.js' %}" ></script>
	<script type="text/javascript" src="{% static 'Leaflet.heat/leaflet-heat.js' %}"></script>
{% endblock %}

{% block content %}

<div class="container" style="margin:10px;">
	<div class="row">
		<div class="col-md-9">
			<h1 style="aling:center;">PILLCO MARCA TURISMO</h1>
		</div>
		<div class="col-md-3 float-md-right">
			<a  href="{% url 'login' %}" target="_blank">
				<button type="button" class="btn btn-primary">Login</button>
			</a>
		</div>
	</div>
</div>
{% endblock %}

{% block jsbody %}
	{% leaflet_map "gis" callback="window.our_layers" %}
	<script type="text/javascript">
		$("#printBtn").click(function(){
			$('#map').print();
		});
	</script>
	<script type="text/javascript" src="https://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>
	<script type="text/javascript" src="{% static 'allwhat/js/main.js' %}"></script>
{% endblock %}

templates/index2.html
<!--
<!DOCTYPE html>
<html>
{% load static %}
{% load leaflet_tags %}
<head>
	{% leaflet_js %}
	{% leaflet_css %}
	<title>Our Home</title>
	<style type="text/css">
		#gis {width: 100%;height:600px;}
	</style>
	<link rel="stylesheet" type="text/css" href="{% static 'routing/leaflet-routing-machine.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/easy-button.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'allwhat/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.css">
	<link rel="stylesheet" type="text/css" href=" {%static 'search-leafleat/leaflet-ais-tracksymbol-search.css' %}">

	<script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}" >	</script>
	<script type="text/javascript" src="{% static 'leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.js' %}" ></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'js/easy-button.js' %}" ></script>
	<script type="text/javascript" src="{% static 'routing/leaflet-routing-machine.js' %}" ></script>
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.0.js" ></script>
	<script type="text/javascript" src="https://unpkg.com/leaflet-geosearch@3.0.0/dist/geosearch.umd.js" ></script>
	<script type="text/javascript" src="{% static 'search-leafleat/leaflet-ais-tracksymbol-search.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'allwhat/js/accion.js' %}"></script>

</head>


<body>
<div class="jaja">Am a hero. Am learning Geodjango </div>

{% leaflet_map "gis" callback="window.our_layers" %}
<script type="text/javascript">
$("#printBtn").click(function(){
  $('#map').print();
});
</script>

<script type="text/javascript">
	function our_layers(map,options){
		var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				maxZoom: 17,
				attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
			});
		var OpenTopoMap = L.tileLayer('http://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
			maxZoom: 17,
			attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
		});


		var points = new L.GeoJSON.AJAX("{% url 'incidences' %}",{
			pointToLayer: function (feature, latlng) {
                return L.marker(latlng, {
                    icon: L.icon({
                        iconUrl: "static/img/alerta.svg",
                        iconSize: [24, 28],
                        iconAnchor: [12, 28],
                        popupAnchor: [0, -25]
                    }),
					title: feature.properties.NAME,
                    riseOnHover: true
                });
            },
			onEachFeature: function(feature,layer){
				layer.bindPopup();
			}

		});

		//datasets.addTo(map);
		points.addTo(map);


		var baseLayers = {
			"OSM": osm,
			"OpenTopoMap":OpenTopoMap
		}

		var groupedOverlays = {
		  "Layers": {
		    "incidences": points
		  }

		};

		L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);
		var routing =  L.Routing.control({
		  waypoints: [
		    L.latLng(-9.9306202, -76.2422333),
		    L.latLng(-9.934950000000001, -76.234818)
		  ]
		}).addTo(map);


		var routing =  L.Routing.control({
		  waypoints: [
		    L.latLng(-9.9306202, -76.2422333),
		    L.latLng(-9.934274, -76.245718)
		  ]
		}).addTo(map);

		//L.easyButton('fa-compass',
		//  function (){
		//    $('.leaflet-routing-container').is(':visible') ? routing.removeFrom(map) : routing.addTo(map)
		//  },
		//  'Routing'
		//).addTo(map);


		function createButton(label, container) {
		    var btn = L.DomUtil.create('button', '', container);
		    btn.setAttribute('type', 'button');
		    btn.innerHTML = label;
		    return btn;
		}

		$("div").remove(".leaflet-routing-container");
		const search = new GeoSearch.GeoSearchControl({
		  provider: new GeoSearch.OpenStreetMapProvider(),
		});
		map.addControl(search);
	}

</script>

</body>
</html>-->

templates/login-acceso.html
{% extends 'template.html' %}
{% load static %}

{% block css %}
<meta charset="utf-8" />
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="{% static 'assets/css/default/style.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/default/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/default/theme/default.css' %}" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->


	<link href="{% static 'assets/plugins/password-indicator/css/password-indicator.css' %}" rel="stylesheet" />

{% endblock %}

{% block jshead %}

{% endblock %}

{% block content %}
<div class="login">
        <div class="login-header">
            <div class="brand">
                <span class="logo"></span><b>MDPM</b>
                <small><h4>SISTEMA DE TURISMO PILLCO MARCA</h4></small>
            </div>
        </div>
        <div class="login-content">
            <form   method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control"  name="username" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Ingresar</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block jsbody %}

{% endblock %}

templates/portal/index.html
{% extends 'template.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'allwhat/css/portal.css' %}">
{% endblock css %}
{% block jsb %}
<script src="{% static 'allwhat/js/localizacion.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBh0f81P4tElzvvyFRmljeRrLpZ-b-8I_A&libraries=places&callback=initMap"
        async defer></script>
{% endblock jsb %}
{% block content %}
<div class="pac-card" id="pac-card">
    <div>
        <div class="container">
            <div class="col-lg-6 col-md-6" style="margin-top:5px;">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Nueva Incidencia</button>
            </div>
        </div>
        <div id="country-selector" class="pac-controls">
        </div>
    </div>
    <div id="pac-container">
        <input id="pac-input" class="form-control" type="text" placeholder="Ingrese Dirección">
    </div>
</div>
<div id="map"></div>
<div id="infowindow-content">
    <img src="" width="16" height="16" id="place-icon">
    <span id="place-name"  class="title"></span><br>
    <span id="place-address"></span>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'incidencia' %}" method="post"> {% csrf_token %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Agraviado:</label>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="documento"  name="documento" placeholder="Ingrese DNI">
                            </div>
                            <div class="col-lg-4">
                                <a type="button" class="btn btn-primary" onclick="loadDoc()">Buscar</a>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="apepaterno" placeholder="Apellido Paterno" readonly required>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="apematerno" placeholder="Apellido Materno" readonly required>
                            </div>
                            <div class="col-lg-4">
                                <input type="text" class="form-control" id="nombres" placeholder="Nombres" readonly required>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-3">
                                <label class="col-form-label">Agente:</label>
                            </div>
                            <div class="col-lg-9">
                                <select class="form-control" onchange="crearpersona()" name="agente_id">
                                    <option value="">Seleccionar Agente</option>
                                    {% for inci in incidencias %}
                                    <option value="{{ inci.id }}">{{inci.apepaterno}} {{ inci.apematerno }} {{ inci.nombre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-3">
                                <label class="col-form-label">Vehiculo:</label>
                            </div>
                            <div class="col-lg-9">
                                <select class="form-control" name="vehiculo_id">
                                    <option value="">Seleccionar Vehiculo</option>
                                    {% for vehi in vehiculos %}
                                    <option value="{{ vehi.id }}">{{vehi.get_modelo_display}} {{ vehi.placa }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-3">
                                <label class="col-form-label">Tipo Incidencia:</label>
                            </div>
                            <div class="col-lg-9">
                                <select class="form-control" name="typeinsidence_id">
                                    <option value="">Seleccionar Incidencia</option>
                                    {% for typeince in typeincidence %}
                                    <option value="{{ typeince.id }}">{{ typeince.descripcion }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <input type="hidden" id="latitude" name="latitude">
                            <input type="hidden" id="longitude" name="longitude">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}
{% block jsbody %}
<script src="{% static 'allwhat/js/localizacion.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBh0f81P4tElzvvyFRmljeRrLpZ-b-8I_A&libraries=places&callback=initMap"
        async defer></script>
{% endblock %}

templates/template.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    {% block mapaleaflet %}
    {% endblock %}
    <title>TURISMO PILLCO MARCA</title>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
    {% block css %}
    {% endblock %}
    {% block jshead %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.0.js" ></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}" >	</script>
    {% block jsbody %}
    {% endblock %}
</body>
</html>